# Change these first
owner: cpe-lab # Your GitHub organization or username, where this repository lives
repo: status.cpe-lab.com # The name of this repository

sites:
  - name: Mikrotik-1
    url: http://mikrotik-1.cpe-lab.com:9980/
  - name: Mikrotik-2
    url: http://mikrotik-2.cpe-lab.com:9980/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cpe-lab.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: night
  introTitle: "System status"
  introMessage: "System uptime thingy goes here"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
